version: '3'
services:
  kibana:
    image: ci-tool-stack/kibana:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.${VERSION:-latest}
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
    environment:
      - SERVER_NAME=kibana.example.org
      - ELASTICSEARCH_URL=http://elasticsearch.example.org
#     volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
networks:
  esnet:
